http:
  listener:
    host: "localhost"
    port: "8081"
    path: "/TravelOnTripCall/{serviceType}"
    
db:
  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "Krishna.2"
    database: "emp"
  
    